# Generated by Django 4.1.4 on 2022-12-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTime', models.CharField(max_length=20)),
                ('breakTime', models.CharField(max_length=20)),
            ],
        ),
    ]
