# Generated by Django 4.1.4 on 2022-12-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='completedTimers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='monthlyCompletedTimers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='monthlyDistractions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='totalDistractions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='breakTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='workTime',
            field=models.IntegerField(),
        ),
    ]
