# Generated by Django 4.1.4 on 2022-12-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_completedtimers_data_monthlycompletedtimers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='breakTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='workTime',
            field=models.IntegerField(default=0),
        ),
    ]
