# Generated by Django 4.1.4 on 2022-12-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_data_user_data_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='userId',
            new_name='idKey',
        ),
    ]
