# Generated by Django 4.1.4 on 2022-12-21 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_rename_userid_data_idkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='idKey',
            field=models.CharField(default='', max_length=16),
        ),
    ]
