# Generated by Django 4.1.4 on 2022-12-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_data_user_alter_data_idkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.AlterField(
            model_name='data',
            name='idKey',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
