# Generated by Django 4.1.4 on 2022-12-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_data_user_alter_data_idkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idKey', models.CharField(default='', max_length=16, unique=True)),
                ('completedTimers', models.IntegerField(default=0)),
                ('totalDistractions', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='completedTimers',
        ),
        migrations.RemoveField(
            model_name='data',
            name='monthlyCompletedTimers',
        ),
        migrations.RemoveField(
            model_name='data',
            name='monthlyDistractions',
        ),
        migrations.RemoveField(
            model_name='data',
            name='totalDistractions',
        ),
        migrations.AlterField(
            model_name='data',
            name='idKey',
            field=models.CharField(default='', max_length=16),
        ),
    ]
