# Generated by Django 4.1.4 on 2022-12-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_overallstats_remove_data_completedtimers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sessionDistractions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='fifteenWorkTimeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='tenWorkTimeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='thirtyWorkTimeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='twentyFiveWorkTimeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='twentyWorkTimeCount',
            field=models.IntegerField(default=0),
        ),
    ]
